### PR TITLE
Add Agoo and benchmarks

### PR DESCRIPTION
**Pull request by ohler55**
The Agoo web server was added to the README.md and a benchmark subdirectory was added. In the benchmark directory are sample files to run all the mentioned web servers and to benchmark each one. I was only able to get half working but the rest are summarized in a table in the benchmark.md file. The bench.rb file can be used to run the benchmarks.

### CODE REVIEW

**Comment by geraldb** [comment]
@ohler55 Wow. Thanks for adding Agoo and for adding benchmarks. Keep it up. Cheers.

PS: If you're interested you're welcome to join the planet ruby org so you can edit in-place (without any pull request, etc.)  If you're interested I will send you an invitation (via github per email). Just let me know. Greetings from Vienna. Cheers. Prost.

**Comment by ohler55** [comment]
I would be honored to be a member of planet ruby. Vienna, nice my wife and I were there a few years ago. She ran the Vienna marathon and we bosh ran with the local HHH group. We have friends in Vienna so we may get back there again some day.

**Comment by geraldb** [comment]
@ohler55 Great. Welcome.  Note: You will get an invitation (by email from GitHub) to join the Planet Ruby org as a member. If you accept, you can update the page in your browser  - no longer any need for a pull request - and you will show up in the people page too (if you set your preference to public - default is private; change the setting in the [github org people page](https://github.com/orgs/planetruby/people)).

**Comment by geraldb** [comment]
Great that to hear that you had a great time in Vienna. The marathon is upcoming in spring (April). Right now it's freezing cold  -10 below zero (thanks to continental air coming from Siberia). Cheers.

**Pull request merged**
